### ISSUE TITLE
Missing ItemProcessor File

### ISSUE THREAD

**Issue by iamkarsoft** [roach-php/laravel#10]
Hello,
Thanks for all the hard work on this package.
Could you please add the ItemProcessor File to the package as you did in the example project?

**Comment by ksassnowski** [comment]
I'm not sure I understand the question. What file are your talking about exactly?

**Comment by iamkarsoft** [comment]
This file is missing when i install roach-php and roach-php laravel. I needed to look at your example repo to create it
<img width="1552" alt="Screenshot 2022-04-19 at 11 30 24 PM" src="https://user-images.githubusercontent.com/5146869/164118012-0a656bee-d3b1-4f0b-920c-8449d97513fc.png">

But these are the files that i see after fresh installation where the ItemProcessor is missing. Unless i'm missing something
<img width="1351" alt="Screenshot 2022-04-19 at 11 32 40 PM" src="https://user-images.githubusercontent.com/5146869/164117946-14a7dece-8c2a-47ec-8521-3d2f945bbaf4.png">

**Comment by ksassnowski** [comment]
Oh I see now, you were looking at the example repository. That repo uses a fairly old version of Roach which is why it still references a `ItemProcessor` file. That base class has since been removed. To create an item processor, you should now directly implement the `ItemProcessorInterface`. Here's the relevant section of the docs https://roach-php.dev/docs/item-pipeline/#writing-item-processors

Sorry for the confusion.
